version: '3'

services:
  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
  web_app:
    build: ./web_app
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
  machine_learning_client:
    build: ./machine_learning_client
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
