name: web_app CI / CD
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Set up docker network, mongodb container, test container
        run: |
        docker network create project4
        docker run --name mongodb -d -p 27017:27017 --network project4 mongo
        docker build -t test_image . 
        docker run -it --rm --name test_container --network project4 test_image 